apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: "stockquote-stockquote"
    chart: "stockquote-1.0.0"
    release: "stocktrade"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
